
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `admin_operation_logs` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model admin_operation_logs
 * This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
 */
export type admin_operation_logsModel = runtime.Types.Result.DefaultSelection<Prisma.$admin_operation_logsPayload>

export type AggregateAdmin_operation_logs = {
  _count: Admin_operation_logsCountAggregateOutputType | null
  _min: Admin_operation_logsMinAggregateOutputType | null
  _max: Admin_operation_logsMaxAggregateOutputType | null
}

export type Admin_operation_logsMinAggregateOutputType = {
  id: string | null
  admin_id: string | null
  action_type: string | null
  target_id: string | null
  detail: string | null
  ip: string | null
  created_time: Date | null
}

export type Admin_operation_logsMaxAggregateOutputType = {
  id: string | null
  admin_id: string | null
  action_type: string | null
  target_id: string | null
  detail: string | null
  ip: string | null
  created_time: Date | null
}

export type Admin_operation_logsCountAggregateOutputType = {
  id: number
  admin_id: number
  action_type: number
  target_id: number
  detail: number
  ip: number
  created_time: number
  _all: number
}


export type Admin_operation_logsMinAggregateInputType = {
  id?: true
  admin_id?: true
  action_type?: true
  target_id?: true
  detail?: true
  ip?: true
  created_time?: true
}

export type Admin_operation_logsMaxAggregateInputType = {
  id?: true
  admin_id?: true
  action_type?: true
  target_id?: true
  detail?: true
  ip?: true
  created_time?: true
}

export type Admin_operation_logsCountAggregateInputType = {
  id?: true
  admin_id?: true
  action_type?: true
  target_id?: true
  detail?: true
  ip?: true
  created_time?: true
  _all?: true
}

export type Admin_operation_logsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which admin_operation_logs to aggregate.
   */
  where?: Prisma.admin_operation_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of admin_operation_logs to fetch.
   */
  orderBy?: Prisma.admin_operation_logsOrderByWithRelationInput | Prisma.admin_operation_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.admin_operation_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` admin_operation_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` admin_operation_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned admin_operation_logs
  **/
  _count?: true | Admin_operation_logsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Admin_operation_logsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Admin_operation_logsMaxAggregateInputType
}

export type GetAdmin_operation_logsAggregateType<T extends Admin_operation_logsAggregateArgs> = {
      [P in keyof T & keyof AggregateAdmin_operation_logs]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAdmin_operation_logs[P]>
    : Prisma.GetScalarType<T[P], AggregateAdmin_operation_logs[P]>
}




export type admin_operation_logsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.admin_operation_logsWhereInput
  orderBy?: Prisma.admin_operation_logsOrderByWithAggregationInput | Prisma.admin_operation_logsOrderByWithAggregationInput[]
  by: Prisma.Admin_operation_logsScalarFieldEnum[] | Prisma.Admin_operation_logsScalarFieldEnum
  having?: Prisma.admin_operation_logsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Admin_operation_logsCountAggregateInputType | true
  _min?: Admin_operation_logsMinAggregateInputType
  _max?: Admin_operation_logsMaxAggregateInputType
}

export type Admin_operation_logsGroupByOutputType = {
  id: string
  admin_id: string
  action_type: string
  target_id: string | null
  detail: string | null
  ip: string | null
  created_time: Date | null
  _count: Admin_operation_logsCountAggregateOutputType | null
  _min: Admin_operation_logsMinAggregateOutputType | null
  _max: Admin_operation_logsMaxAggregateOutputType | null
}

type GetAdmin_operation_logsGroupByPayload<T extends admin_operation_logsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Admin_operation_logsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Admin_operation_logsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Admin_operation_logsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Admin_operation_logsGroupByOutputType[P]>
      }
    >
  >



export type admin_operation_logsWhereInput = {
  AND?: Prisma.admin_operation_logsWhereInput | Prisma.admin_operation_logsWhereInput[]
  OR?: Prisma.admin_operation_logsWhereInput[]
  NOT?: Prisma.admin_operation_logsWhereInput | Prisma.admin_operation_logsWhereInput[]
  id?: Prisma.UuidFilter<"admin_operation_logs"> | string
  admin_id?: Prisma.UuidFilter<"admin_operation_logs"> | string
  action_type?: Prisma.StringFilter<"admin_operation_logs"> | string
  target_id?: Prisma.StringNullableFilter<"admin_operation_logs"> | string | null
  detail?: Prisma.StringNullableFilter<"admin_operation_logs"> | string | null
  ip?: Prisma.StringNullableFilter<"admin_operation_logs"> | string | null
  created_time?: Prisma.DateTimeNullableFilter<"admin_operation_logs"> | Date | string | null
}

export type admin_operation_logsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  admin_id?: Prisma.SortOrder
  action_type?: Prisma.SortOrder
  target_id?: Prisma.SortOrderInput | Prisma.SortOrder
  detail?: Prisma.SortOrderInput | Prisma.SortOrder
  ip?: Prisma.SortOrderInput | Prisma.SortOrder
  created_time?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type admin_operation_logsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.admin_operation_logsWhereInput | Prisma.admin_operation_logsWhereInput[]
  OR?: Prisma.admin_operation_logsWhereInput[]
  NOT?: Prisma.admin_operation_logsWhereInput | Prisma.admin_operation_logsWhereInput[]
  admin_id?: Prisma.UuidFilter<"admin_operation_logs"> | string
  action_type?: Prisma.StringFilter<"admin_operation_logs"> | string
  target_id?: Prisma.StringNullableFilter<"admin_operation_logs"> | string | null
  detail?: Prisma.StringNullableFilter<"admin_operation_logs"> | string | null
  ip?: Prisma.StringNullableFilter<"admin_operation_logs"> | string | null
  created_time?: Prisma.DateTimeNullableFilter<"admin_operation_logs"> | Date | string | null
}, "id">

export type admin_operation_logsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  admin_id?: Prisma.SortOrder
  action_type?: Prisma.SortOrder
  target_id?: Prisma.SortOrderInput | Prisma.SortOrder
  detail?: Prisma.SortOrderInput | Prisma.SortOrder
  ip?: Prisma.SortOrderInput | Prisma.SortOrder
  created_time?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.admin_operation_logsCountOrderByAggregateInput
  _max?: Prisma.admin_operation_logsMaxOrderByAggregateInput
  _min?: Prisma.admin_operation_logsMinOrderByAggregateInput
}

export type admin_operation_logsScalarWhereWithAggregatesInput = {
  AND?: Prisma.admin_operation_logsScalarWhereWithAggregatesInput | Prisma.admin_operation_logsScalarWhereWithAggregatesInput[]
  OR?: Prisma.admin_operation_logsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.admin_operation_logsScalarWhereWithAggregatesInput | Prisma.admin_operation_logsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"admin_operation_logs"> | string
  admin_id?: Prisma.UuidWithAggregatesFilter<"admin_operation_logs"> | string
  action_type?: Prisma.StringWithAggregatesFilter<"admin_operation_logs"> | string
  target_id?: Prisma.StringNullableWithAggregatesFilter<"admin_operation_logs"> | string | null
  detail?: Prisma.StringNullableWithAggregatesFilter<"admin_operation_logs"> | string | null
  ip?: Prisma.StringNullableWithAggregatesFilter<"admin_operation_logs"> | string | null
  created_time?: Prisma.DateTimeNullableWithAggregatesFilter<"admin_operation_logs"> | Date | string | null
}

export type admin_operation_logsCreateInput = {
  id?: string
  admin_id: string
  action_type: string
  target_id?: string | null
  detail?: string | null
  ip?: string | null
  created_time?: Date | string | null
}

export type admin_operation_logsUncheckedCreateInput = {
  id?: string
  admin_id: string
  action_type: string
  target_id?: string | null
  detail?: string | null
  ip?: string | null
  created_time?: Date | string | null
}

export type admin_operation_logsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  admin_id?: Prisma.StringFieldUpdateOperationsInput | string
  action_type?: Prisma.StringFieldUpdateOperationsInput | string
  target_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type admin_operation_logsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  admin_id?: Prisma.StringFieldUpdateOperationsInput | string
  action_type?: Prisma.StringFieldUpdateOperationsInput | string
  target_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type admin_operation_logsCreateManyInput = {
  id?: string
  admin_id: string
  action_type: string
  target_id?: string | null
  detail?: string | null
  ip?: string | null
  created_time?: Date | string | null
}

export type admin_operation_logsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  admin_id?: Prisma.StringFieldUpdateOperationsInput | string
  action_type?: Prisma.StringFieldUpdateOperationsInput | string
  target_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type admin_operation_logsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  admin_id?: Prisma.StringFieldUpdateOperationsInput | string
  action_type?: Prisma.StringFieldUpdateOperationsInput | string
  target_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type admin_operation_logsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  admin_id?: Prisma.SortOrder
  action_type?: Prisma.SortOrder
  target_id?: Prisma.SortOrder
  detail?: Prisma.SortOrder
  ip?: Prisma.SortOrder
  created_time?: Prisma.SortOrder
}

export type admin_operation_logsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  admin_id?: Prisma.SortOrder
  action_type?: Prisma.SortOrder
  target_id?: Prisma.SortOrder
  detail?: Prisma.SortOrder
  ip?: Prisma.SortOrder
  created_time?: Prisma.SortOrder
}

export type admin_operation_logsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  admin_id?: Prisma.SortOrder
  action_type?: Prisma.SortOrder
  target_id?: Prisma.SortOrder
  detail?: Prisma.SortOrder
  ip?: Prisma.SortOrder
  created_time?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type admin_operation_logsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  admin_id?: boolean
  action_type?: boolean
  target_id?: boolean
  detail?: boolean
  ip?: boolean
  created_time?: boolean
}, ExtArgs["result"]["admin_operation_logs"]>

export type admin_operation_logsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  admin_id?: boolean
  action_type?: boolean
  target_id?: boolean
  detail?: boolean
  ip?: boolean
  created_time?: boolean
}, ExtArgs["result"]["admin_operation_logs"]>

export type admin_operation_logsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  admin_id?: boolean
  action_type?: boolean
  target_id?: boolean
  detail?: boolean
  ip?: boolean
  created_time?: boolean
}, ExtArgs["result"]["admin_operation_logs"]>

export type admin_operation_logsSelectScalar = {
  id?: boolean
  admin_id?: boolean
  action_type?: boolean
  target_id?: boolean
  detail?: boolean
  ip?: boolean
  created_time?: boolean
}

export type admin_operation_logsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "admin_id" | "action_type" | "target_id" | "detail" | "ip" | "created_time", ExtArgs["result"]["admin_operation_logs"]>

export type $admin_operation_logsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "admin_operation_logs"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    admin_id: string
    action_type: string
    target_id: string | null
    detail: string | null
    ip: string | null
    created_time: Date | null
  }, ExtArgs["result"]["admin_operation_logs"]>
  composites: {}
}

export type admin_operation_logsGetPayload<S extends boolean | null | undefined | admin_operation_logsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload, S>

export type admin_operation_logsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<admin_operation_logsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Admin_operation_logsCountAggregateInputType | true
  }

export interface admin_operation_logsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['admin_operation_logs'], meta: { name: 'admin_operation_logs' } }
  /**
   * Find zero or one Admin_operation_logs that matches the filter.
   * @param {admin_operation_logsFindUniqueArgs} args - Arguments to find a Admin_operation_logs
   * @example
   * // Get one Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends admin_operation_logsFindUniqueArgs>(args: Prisma.SelectSubset<T, admin_operation_logsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__admin_operation_logsClient<runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Admin_operation_logs that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {admin_operation_logsFindUniqueOrThrowArgs} args - Arguments to find a Admin_operation_logs
   * @example
   * // Get one Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends admin_operation_logsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, admin_operation_logsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__admin_operation_logsClient<runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Admin_operation_logs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {admin_operation_logsFindFirstArgs} args - Arguments to find a Admin_operation_logs
   * @example
   * // Get one Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends admin_operation_logsFindFirstArgs>(args?: Prisma.SelectSubset<T, admin_operation_logsFindFirstArgs<ExtArgs>>): Prisma.Prisma__admin_operation_logsClient<runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Admin_operation_logs that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {admin_operation_logsFindFirstOrThrowArgs} args - Arguments to find a Admin_operation_logs
   * @example
   * // Get one Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends admin_operation_logsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, admin_operation_logsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__admin_operation_logsClient<runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Admin_operation_logs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {admin_operation_logsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.findMany()
   * 
   * // Get first 10 Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const admin_operation_logsWithIdOnly = await prisma.admin_operation_logs.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends admin_operation_logsFindManyArgs>(args?: Prisma.SelectSubset<T, admin_operation_logsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Admin_operation_logs.
   * @param {admin_operation_logsCreateArgs} args - Arguments to create a Admin_operation_logs.
   * @example
   * // Create one Admin_operation_logs
   * const Admin_operation_logs = await prisma.admin_operation_logs.create({
   *   data: {
   *     // ... data to create a Admin_operation_logs
   *   }
   * })
   * 
   */
  create<T extends admin_operation_logsCreateArgs>(args: Prisma.SelectSubset<T, admin_operation_logsCreateArgs<ExtArgs>>): Prisma.Prisma__admin_operation_logsClient<runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Admin_operation_logs.
   * @param {admin_operation_logsCreateManyArgs} args - Arguments to create many Admin_operation_logs.
   * @example
   * // Create many Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends admin_operation_logsCreateManyArgs>(args?: Prisma.SelectSubset<T, admin_operation_logsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Admin_operation_logs and returns the data saved in the database.
   * @param {admin_operation_logsCreateManyAndReturnArgs} args - Arguments to create many Admin_operation_logs.
   * @example
   * // Create many Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Admin_operation_logs and only return the `id`
   * const admin_operation_logsWithIdOnly = await prisma.admin_operation_logs.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends admin_operation_logsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, admin_operation_logsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Admin_operation_logs.
   * @param {admin_operation_logsDeleteArgs} args - Arguments to delete one Admin_operation_logs.
   * @example
   * // Delete one Admin_operation_logs
   * const Admin_operation_logs = await prisma.admin_operation_logs.delete({
   *   where: {
   *     // ... filter to delete one Admin_operation_logs
   *   }
   * })
   * 
   */
  delete<T extends admin_operation_logsDeleteArgs>(args: Prisma.SelectSubset<T, admin_operation_logsDeleteArgs<ExtArgs>>): Prisma.Prisma__admin_operation_logsClient<runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Admin_operation_logs.
   * @param {admin_operation_logsUpdateArgs} args - Arguments to update one Admin_operation_logs.
   * @example
   * // Update one Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends admin_operation_logsUpdateArgs>(args: Prisma.SelectSubset<T, admin_operation_logsUpdateArgs<ExtArgs>>): Prisma.Prisma__admin_operation_logsClient<runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Admin_operation_logs.
   * @param {admin_operation_logsDeleteManyArgs} args - Arguments to filter Admin_operation_logs to delete.
   * @example
   * // Delete a few Admin_operation_logs
   * const { count } = await prisma.admin_operation_logs.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends admin_operation_logsDeleteManyArgs>(args?: Prisma.SelectSubset<T, admin_operation_logsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Admin_operation_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {admin_operation_logsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends admin_operation_logsUpdateManyArgs>(args: Prisma.SelectSubset<T, admin_operation_logsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Admin_operation_logs and returns the data updated in the database.
   * @param {admin_operation_logsUpdateManyAndReturnArgs} args - Arguments to update many Admin_operation_logs.
   * @example
   * // Update many Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Admin_operation_logs and only return the `id`
   * const admin_operation_logsWithIdOnly = await prisma.admin_operation_logs.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends admin_operation_logsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, admin_operation_logsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Admin_operation_logs.
   * @param {admin_operation_logsUpsertArgs} args - Arguments to update or create a Admin_operation_logs.
   * @example
   * // Update or create a Admin_operation_logs
   * const admin_operation_logs = await prisma.admin_operation_logs.upsert({
   *   create: {
   *     // ... data to create a Admin_operation_logs
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Admin_operation_logs we want to update
   *   }
   * })
   */
  upsert<T extends admin_operation_logsUpsertArgs>(args: Prisma.SelectSubset<T, admin_operation_logsUpsertArgs<ExtArgs>>): Prisma.Prisma__admin_operation_logsClient<runtime.Types.Result.GetResult<Prisma.$admin_operation_logsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Admin_operation_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {admin_operation_logsCountArgs} args - Arguments to filter Admin_operation_logs to count.
   * @example
   * // Count the number of Admin_operation_logs
   * const count = await prisma.admin_operation_logs.count({
   *   where: {
   *     // ... the filter for the Admin_operation_logs we want to count
   *   }
   * })
  **/
  count<T extends admin_operation_logsCountArgs>(
    args?: Prisma.Subset<T, admin_operation_logsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Admin_operation_logsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Admin_operation_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Admin_operation_logsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Admin_operation_logsAggregateArgs>(args: Prisma.Subset<T, Admin_operation_logsAggregateArgs>): Prisma.PrismaPromise<GetAdmin_operation_logsAggregateType<T>>

  /**
   * Group by Admin_operation_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {admin_operation_logsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends admin_operation_logsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: admin_operation_logsGroupByArgs['orderBy'] }
      : { orderBy?: admin_operation_logsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, admin_operation_logsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAdmin_operation_logsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the admin_operation_logs model
 */
readonly fields: admin_operation_logsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for admin_operation_logs.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__admin_operation_logsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the admin_operation_logs model
 */
export interface admin_operation_logsFieldRefs {
  readonly id: Prisma.FieldRef<"admin_operation_logs", 'String'>
  readonly admin_id: Prisma.FieldRef<"admin_operation_logs", 'String'>
  readonly action_type: Prisma.FieldRef<"admin_operation_logs", 'String'>
  readonly target_id: Prisma.FieldRef<"admin_operation_logs", 'String'>
  readonly detail: Prisma.FieldRef<"admin_operation_logs", 'String'>
  readonly ip: Prisma.FieldRef<"admin_operation_logs", 'String'>
  readonly created_time: Prisma.FieldRef<"admin_operation_logs", 'DateTime'>
}
    

// Custom InputTypes
/**
 * admin_operation_logs findUnique
 */
export type admin_operation_logsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
  /**
   * Filter, which admin_operation_logs to fetch.
   */
  where: Prisma.admin_operation_logsWhereUniqueInput
}

/**
 * admin_operation_logs findUniqueOrThrow
 */
export type admin_operation_logsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
  /**
   * Filter, which admin_operation_logs to fetch.
   */
  where: Prisma.admin_operation_logsWhereUniqueInput
}

/**
 * admin_operation_logs findFirst
 */
export type admin_operation_logsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
  /**
   * Filter, which admin_operation_logs to fetch.
   */
  where?: Prisma.admin_operation_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of admin_operation_logs to fetch.
   */
  orderBy?: Prisma.admin_operation_logsOrderByWithRelationInput | Prisma.admin_operation_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for admin_operation_logs.
   */
  cursor?: Prisma.admin_operation_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` admin_operation_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` admin_operation_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of admin_operation_logs.
   */
  distinct?: Prisma.Admin_operation_logsScalarFieldEnum | Prisma.Admin_operation_logsScalarFieldEnum[]
}

/**
 * admin_operation_logs findFirstOrThrow
 */
export type admin_operation_logsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
  /**
   * Filter, which admin_operation_logs to fetch.
   */
  where?: Prisma.admin_operation_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of admin_operation_logs to fetch.
   */
  orderBy?: Prisma.admin_operation_logsOrderByWithRelationInput | Prisma.admin_operation_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for admin_operation_logs.
   */
  cursor?: Prisma.admin_operation_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` admin_operation_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` admin_operation_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of admin_operation_logs.
   */
  distinct?: Prisma.Admin_operation_logsScalarFieldEnum | Prisma.Admin_operation_logsScalarFieldEnum[]
}

/**
 * admin_operation_logs findMany
 */
export type admin_operation_logsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
  /**
   * Filter, which admin_operation_logs to fetch.
   */
  where?: Prisma.admin_operation_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of admin_operation_logs to fetch.
   */
  orderBy?: Prisma.admin_operation_logsOrderByWithRelationInput | Prisma.admin_operation_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing admin_operation_logs.
   */
  cursor?: Prisma.admin_operation_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` admin_operation_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` admin_operation_logs.
   */
  skip?: number
  distinct?: Prisma.Admin_operation_logsScalarFieldEnum | Prisma.Admin_operation_logsScalarFieldEnum[]
}

/**
 * admin_operation_logs create
 */
export type admin_operation_logsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
  /**
   * The data needed to create a admin_operation_logs.
   */
  data: Prisma.XOR<Prisma.admin_operation_logsCreateInput, Prisma.admin_operation_logsUncheckedCreateInput>
}

/**
 * admin_operation_logs createMany
 */
export type admin_operation_logsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many admin_operation_logs.
   */
  data: Prisma.admin_operation_logsCreateManyInput | Prisma.admin_operation_logsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * admin_operation_logs createManyAndReturn
 */
export type admin_operation_logsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
  /**
   * The data used to create many admin_operation_logs.
   */
  data: Prisma.admin_operation_logsCreateManyInput | Prisma.admin_operation_logsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * admin_operation_logs update
 */
export type admin_operation_logsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
  /**
   * The data needed to update a admin_operation_logs.
   */
  data: Prisma.XOR<Prisma.admin_operation_logsUpdateInput, Prisma.admin_operation_logsUncheckedUpdateInput>
  /**
   * Choose, which admin_operation_logs to update.
   */
  where: Prisma.admin_operation_logsWhereUniqueInput
}

/**
 * admin_operation_logs updateMany
 */
export type admin_operation_logsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update admin_operation_logs.
   */
  data: Prisma.XOR<Prisma.admin_operation_logsUpdateManyMutationInput, Prisma.admin_operation_logsUncheckedUpdateManyInput>
  /**
   * Filter which admin_operation_logs to update
   */
  where?: Prisma.admin_operation_logsWhereInput
  /**
   * Limit how many admin_operation_logs to update.
   */
  limit?: number
}

/**
 * admin_operation_logs updateManyAndReturn
 */
export type admin_operation_logsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
  /**
   * The data used to update admin_operation_logs.
   */
  data: Prisma.XOR<Prisma.admin_operation_logsUpdateManyMutationInput, Prisma.admin_operation_logsUncheckedUpdateManyInput>
  /**
   * Filter which admin_operation_logs to update
   */
  where?: Prisma.admin_operation_logsWhereInput
  /**
   * Limit how many admin_operation_logs to update.
   */
  limit?: number
}

/**
 * admin_operation_logs upsert
 */
export type admin_operation_logsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
  /**
   * The filter to search for the admin_operation_logs to update in case it exists.
   */
  where: Prisma.admin_operation_logsWhereUniqueInput
  /**
   * In case the admin_operation_logs found by the `where` argument doesn't exist, create a new admin_operation_logs with this data.
   */
  create: Prisma.XOR<Prisma.admin_operation_logsCreateInput, Prisma.admin_operation_logsUncheckedCreateInput>
  /**
   * In case the admin_operation_logs was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.admin_operation_logsUpdateInput, Prisma.admin_operation_logsUncheckedUpdateInput>
}

/**
 * admin_operation_logs delete
 */
export type admin_operation_logsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
  /**
   * Filter which admin_operation_logs to delete.
   */
  where: Prisma.admin_operation_logsWhereUniqueInput
}

/**
 * admin_operation_logs deleteMany
 */
export type admin_operation_logsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which admin_operation_logs to delete
   */
  where?: Prisma.admin_operation_logsWhereInput
  /**
   * Limit how many admin_operation_logs to delete.
   */
  limit?: number
}

/**
 * admin_operation_logs without action
 */
export type admin_operation_logsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the admin_operation_logs
   */
  select?: Prisma.admin_operation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the admin_operation_logs
   */
  omit?: Prisma.admin_operation_logsOmit<ExtArgs> | null
}
