
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `mail_histories` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model mail_histories
 * This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
 */
export type mail_historiesModel = runtime.Types.Result.DefaultSelection<Prisma.$mail_historiesPayload>

export type AggregateMail_histories = {
  _count: Mail_historiesCountAggregateOutputType | null
  _min: Mail_historiesMinAggregateOutputType | null
  _max: Mail_historiesMaxAggregateOutputType | null
}

export type Mail_historiesMinAggregateOutputType = {
  id: string | null
  user_id: string | null
  audit_log_id: string | null
  scene: string | null
  tone: string | null
  recipient_name: string | null
  sender_name: string | null
  core_points: string | null
  mail_content: string | null
  is_favorite: boolean | null
  is_deleted: boolean | null
  created_time: Date | null
  updated_time: Date | null
}

export type Mail_historiesMaxAggregateOutputType = {
  id: string | null
  user_id: string | null
  audit_log_id: string | null
  scene: string | null
  tone: string | null
  recipient_name: string | null
  sender_name: string | null
  core_points: string | null
  mail_content: string | null
  is_favorite: boolean | null
  is_deleted: boolean | null
  created_time: Date | null
  updated_time: Date | null
}

export type Mail_historiesCountAggregateOutputType = {
  id: number
  user_id: number
  audit_log_id: number
  scene: number
  tone: number
  recipient_name: number
  sender_name: number
  core_points: number
  mail_content: number
  is_favorite: number
  is_deleted: number
  created_time: number
  updated_time: number
  _all: number
}


export type Mail_historiesMinAggregateInputType = {
  id?: true
  user_id?: true
  audit_log_id?: true
  scene?: true
  tone?: true
  recipient_name?: true
  sender_name?: true
  core_points?: true
  mail_content?: true
  is_favorite?: true
  is_deleted?: true
  created_time?: true
  updated_time?: true
}

export type Mail_historiesMaxAggregateInputType = {
  id?: true
  user_id?: true
  audit_log_id?: true
  scene?: true
  tone?: true
  recipient_name?: true
  sender_name?: true
  core_points?: true
  mail_content?: true
  is_favorite?: true
  is_deleted?: true
  created_time?: true
  updated_time?: true
}

export type Mail_historiesCountAggregateInputType = {
  id?: true
  user_id?: true
  audit_log_id?: true
  scene?: true
  tone?: true
  recipient_name?: true
  sender_name?: true
  core_points?: true
  mail_content?: true
  is_favorite?: true
  is_deleted?: true
  created_time?: true
  updated_time?: true
  _all?: true
}

export type Mail_historiesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which mail_histories to aggregate.
   */
  where?: Prisma.mail_historiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of mail_histories to fetch.
   */
  orderBy?: Prisma.mail_historiesOrderByWithRelationInput | Prisma.mail_historiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.mail_historiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` mail_histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` mail_histories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned mail_histories
  **/
  _count?: true | Mail_historiesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Mail_historiesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Mail_historiesMaxAggregateInputType
}

export type GetMail_historiesAggregateType<T extends Mail_historiesAggregateArgs> = {
      [P in keyof T & keyof AggregateMail_histories]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMail_histories[P]>
    : Prisma.GetScalarType<T[P], AggregateMail_histories[P]>
}




export type mail_historiesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.mail_historiesWhereInput
  orderBy?: Prisma.mail_historiesOrderByWithAggregationInput | Prisma.mail_historiesOrderByWithAggregationInput[]
  by: Prisma.Mail_historiesScalarFieldEnum[] | Prisma.Mail_historiesScalarFieldEnum
  having?: Prisma.mail_historiesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Mail_historiesCountAggregateInputType | true
  _min?: Mail_historiesMinAggregateInputType
  _max?: Mail_historiesMaxAggregateInputType
}

export type Mail_historiesGroupByOutputType = {
  id: string
  user_id: string
  audit_log_id: string | null
  scene: string | null
  tone: string | null
  recipient_name: string | null
  sender_name: string | null
  core_points: string | null
  mail_content: string
  is_favorite: boolean | null
  is_deleted: boolean | null
  created_time: Date | null
  updated_time: Date | null
  _count: Mail_historiesCountAggregateOutputType | null
  _min: Mail_historiesMinAggregateOutputType | null
  _max: Mail_historiesMaxAggregateOutputType | null
}

type GetMail_historiesGroupByPayload<T extends mail_historiesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Mail_historiesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Mail_historiesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Mail_historiesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Mail_historiesGroupByOutputType[P]>
      }
    >
  >



export type mail_historiesWhereInput = {
  AND?: Prisma.mail_historiesWhereInput | Prisma.mail_historiesWhereInput[]
  OR?: Prisma.mail_historiesWhereInput[]
  NOT?: Prisma.mail_historiesWhereInput | Prisma.mail_historiesWhereInput[]
  id?: Prisma.UuidFilter<"mail_histories"> | string
  user_id?: Prisma.UuidFilter<"mail_histories"> | string
  audit_log_id?: Prisma.UuidNullableFilter<"mail_histories"> | string | null
  scene?: Prisma.StringNullableFilter<"mail_histories"> | string | null
  tone?: Prisma.StringNullableFilter<"mail_histories"> | string | null
  recipient_name?: Prisma.StringNullableFilter<"mail_histories"> | string | null
  sender_name?: Prisma.StringNullableFilter<"mail_histories"> | string | null
  core_points?: Prisma.StringNullableFilter<"mail_histories"> | string | null
  mail_content?: Prisma.StringFilter<"mail_histories"> | string
  is_favorite?: Prisma.BoolNullableFilter<"mail_histories"> | boolean | null
  is_deleted?: Prisma.BoolNullableFilter<"mail_histories"> | boolean | null
  created_time?: Prisma.DateTimeNullableFilter<"mail_histories"> | Date | string | null
  updated_time?: Prisma.DateTimeNullableFilter<"mail_histories"> | Date | string | null
}

export type mail_historiesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  audit_log_id?: Prisma.SortOrderInput | Prisma.SortOrder
  scene?: Prisma.SortOrderInput | Prisma.SortOrder
  tone?: Prisma.SortOrderInput | Prisma.SortOrder
  recipient_name?: Prisma.SortOrderInput | Prisma.SortOrder
  sender_name?: Prisma.SortOrderInput | Prisma.SortOrder
  core_points?: Prisma.SortOrderInput | Prisma.SortOrder
  mail_content?: Prisma.SortOrder
  is_favorite?: Prisma.SortOrderInput | Prisma.SortOrder
  is_deleted?: Prisma.SortOrderInput | Prisma.SortOrder
  created_time?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_time?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type mail_historiesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.mail_historiesWhereInput | Prisma.mail_historiesWhereInput[]
  OR?: Prisma.mail_historiesWhereInput[]
  NOT?: Prisma.mail_historiesWhereInput | Prisma.mail_historiesWhereInput[]
  user_id?: Prisma.UuidFilter<"mail_histories"> | string
  audit_log_id?: Prisma.UuidNullableFilter<"mail_histories"> | string | null
  scene?: Prisma.StringNullableFilter<"mail_histories"> | string | null
  tone?: Prisma.StringNullableFilter<"mail_histories"> | string | null
  recipient_name?: Prisma.StringNullableFilter<"mail_histories"> | string | null
  sender_name?: Prisma.StringNullableFilter<"mail_histories"> | string | null
  core_points?: Prisma.StringNullableFilter<"mail_histories"> | string | null
  mail_content?: Prisma.StringFilter<"mail_histories"> | string
  is_favorite?: Prisma.BoolNullableFilter<"mail_histories"> | boolean | null
  is_deleted?: Prisma.BoolNullableFilter<"mail_histories"> | boolean | null
  created_time?: Prisma.DateTimeNullableFilter<"mail_histories"> | Date | string | null
  updated_time?: Prisma.DateTimeNullableFilter<"mail_histories"> | Date | string | null
}, "id">

export type mail_historiesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  audit_log_id?: Prisma.SortOrderInput | Prisma.SortOrder
  scene?: Prisma.SortOrderInput | Prisma.SortOrder
  tone?: Prisma.SortOrderInput | Prisma.SortOrder
  recipient_name?: Prisma.SortOrderInput | Prisma.SortOrder
  sender_name?: Prisma.SortOrderInput | Prisma.SortOrder
  core_points?: Prisma.SortOrderInput | Prisma.SortOrder
  mail_content?: Prisma.SortOrder
  is_favorite?: Prisma.SortOrderInput | Prisma.SortOrder
  is_deleted?: Prisma.SortOrderInput | Prisma.SortOrder
  created_time?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_time?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.mail_historiesCountOrderByAggregateInput
  _max?: Prisma.mail_historiesMaxOrderByAggregateInput
  _min?: Prisma.mail_historiesMinOrderByAggregateInput
}

export type mail_historiesScalarWhereWithAggregatesInput = {
  AND?: Prisma.mail_historiesScalarWhereWithAggregatesInput | Prisma.mail_historiesScalarWhereWithAggregatesInput[]
  OR?: Prisma.mail_historiesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.mail_historiesScalarWhereWithAggregatesInput | Prisma.mail_historiesScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"mail_histories"> | string
  user_id?: Prisma.UuidWithAggregatesFilter<"mail_histories"> | string
  audit_log_id?: Prisma.UuidNullableWithAggregatesFilter<"mail_histories"> | string | null
  scene?: Prisma.StringNullableWithAggregatesFilter<"mail_histories"> | string | null
  tone?: Prisma.StringNullableWithAggregatesFilter<"mail_histories"> | string | null
  recipient_name?: Prisma.StringNullableWithAggregatesFilter<"mail_histories"> | string | null
  sender_name?: Prisma.StringNullableWithAggregatesFilter<"mail_histories"> | string | null
  core_points?: Prisma.StringNullableWithAggregatesFilter<"mail_histories"> | string | null
  mail_content?: Prisma.StringWithAggregatesFilter<"mail_histories"> | string
  is_favorite?: Prisma.BoolNullableWithAggregatesFilter<"mail_histories"> | boolean | null
  is_deleted?: Prisma.BoolNullableWithAggregatesFilter<"mail_histories"> | boolean | null
  created_time?: Prisma.DateTimeNullableWithAggregatesFilter<"mail_histories"> | Date | string | null
  updated_time?: Prisma.DateTimeNullableWithAggregatesFilter<"mail_histories"> | Date | string | null
}

export type mail_historiesCreateInput = {
  id?: string
  user_id: string
  audit_log_id?: string | null
  scene?: string | null
  tone?: string | null
  recipient_name?: string | null
  sender_name?: string | null
  core_points?: string | null
  mail_content: string
  is_favorite?: boolean | null
  is_deleted?: boolean | null
  created_time?: Date | string | null
  updated_time?: Date | string | null
}

export type mail_historiesUncheckedCreateInput = {
  id?: string
  user_id: string
  audit_log_id?: string | null
  scene?: string | null
  tone?: string | null
  recipient_name?: string | null
  sender_name?: string | null
  core_points?: string | null
  mail_content: string
  is_favorite?: boolean | null
  is_deleted?: boolean | null
  created_time?: Date | string | null
  updated_time?: Date | string | null
}

export type mail_historiesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  audit_log_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scene?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipient_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sender_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  core_points?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mail_content?: Prisma.StringFieldUpdateOperationsInput | string
  is_favorite?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_deleted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type mail_historiesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  audit_log_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scene?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipient_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sender_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  core_points?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mail_content?: Prisma.StringFieldUpdateOperationsInput | string
  is_favorite?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_deleted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type mail_historiesCreateManyInput = {
  id?: string
  user_id: string
  audit_log_id?: string | null
  scene?: string | null
  tone?: string | null
  recipient_name?: string | null
  sender_name?: string | null
  core_points?: string | null
  mail_content: string
  is_favorite?: boolean | null
  is_deleted?: boolean | null
  created_time?: Date | string | null
  updated_time?: Date | string | null
}

export type mail_historiesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  audit_log_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scene?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipient_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sender_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  core_points?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mail_content?: Prisma.StringFieldUpdateOperationsInput | string
  is_favorite?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_deleted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type mail_historiesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  audit_log_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scene?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipient_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sender_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  core_points?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mail_content?: Prisma.StringFieldUpdateOperationsInput | string
  is_favorite?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_deleted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type mail_historiesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  audit_log_id?: Prisma.SortOrder
  scene?: Prisma.SortOrder
  tone?: Prisma.SortOrder
  recipient_name?: Prisma.SortOrder
  sender_name?: Prisma.SortOrder
  core_points?: Prisma.SortOrder
  mail_content?: Prisma.SortOrder
  is_favorite?: Prisma.SortOrder
  is_deleted?: Prisma.SortOrder
  created_time?: Prisma.SortOrder
  updated_time?: Prisma.SortOrder
}

export type mail_historiesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  audit_log_id?: Prisma.SortOrder
  scene?: Prisma.SortOrder
  tone?: Prisma.SortOrder
  recipient_name?: Prisma.SortOrder
  sender_name?: Prisma.SortOrder
  core_points?: Prisma.SortOrder
  mail_content?: Prisma.SortOrder
  is_favorite?: Prisma.SortOrder
  is_deleted?: Prisma.SortOrder
  created_time?: Prisma.SortOrder
  updated_time?: Prisma.SortOrder
}

export type mail_historiesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  audit_log_id?: Prisma.SortOrder
  scene?: Prisma.SortOrder
  tone?: Prisma.SortOrder
  recipient_name?: Prisma.SortOrder
  sender_name?: Prisma.SortOrder
  core_points?: Prisma.SortOrder
  mail_content?: Prisma.SortOrder
  is_favorite?: Prisma.SortOrder
  is_deleted?: Prisma.SortOrder
  created_time?: Prisma.SortOrder
  updated_time?: Prisma.SortOrder
}



export type mail_historiesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  audit_log_id?: boolean
  scene?: boolean
  tone?: boolean
  recipient_name?: boolean
  sender_name?: boolean
  core_points?: boolean
  mail_content?: boolean
  is_favorite?: boolean
  is_deleted?: boolean
  created_time?: boolean
  updated_time?: boolean
}, ExtArgs["result"]["mail_histories"]>

export type mail_historiesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  audit_log_id?: boolean
  scene?: boolean
  tone?: boolean
  recipient_name?: boolean
  sender_name?: boolean
  core_points?: boolean
  mail_content?: boolean
  is_favorite?: boolean
  is_deleted?: boolean
  created_time?: boolean
  updated_time?: boolean
}, ExtArgs["result"]["mail_histories"]>

export type mail_historiesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  audit_log_id?: boolean
  scene?: boolean
  tone?: boolean
  recipient_name?: boolean
  sender_name?: boolean
  core_points?: boolean
  mail_content?: boolean
  is_favorite?: boolean
  is_deleted?: boolean
  created_time?: boolean
  updated_time?: boolean
}, ExtArgs["result"]["mail_histories"]>

export type mail_historiesSelectScalar = {
  id?: boolean
  user_id?: boolean
  audit_log_id?: boolean
  scene?: boolean
  tone?: boolean
  recipient_name?: boolean
  sender_name?: boolean
  core_points?: boolean
  mail_content?: boolean
  is_favorite?: boolean
  is_deleted?: boolean
  created_time?: boolean
  updated_time?: boolean
}

export type mail_historiesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "audit_log_id" | "scene" | "tone" | "recipient_name" | "sender_name" | "core_points" | "mail_content" | "is_favorite" | "is_deleted" | "created_time" | "updated_time", ExtArgs["result"]["mail_histories"]>

export type $mail_historiesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "mail_histories"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_id: string
    audit_log_id: string | null
    scene: string | null
    tone: string | null
    recipient_name: string | null
    sender_name: string | null
    core_points: string | null
    mail_content: string
    is_favorite: boolean | null
    is_deleted: boolean | null
    created_time: Date | null
    updated_time: Date | null
  }, ExtArgs["result"]["mail_histories"]>
  composites: {}
}

export type mail_historiesGetPayload<S extends boolean | null | undefined | mail_historiesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload, S>

export type mail_historiesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<mail_historiesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Mail_historiesCountAggregateInputType | true
  }

export interface mail_historiesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['mail_histories'], meta: { name: 'mail_histories' } }
  /**
   * Find zero or one Mail_histories that matches the filter.
   * @param {mail_historiesFindUniqueArgs} args - Arguments to find a Mail_histories
   * @example
   * // Get one Mail_histories
   * const mail_histories = await prisma.mail_histories.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends mail_historiesFindUniqueArgs>(args: Prisma.SelectSubset<T, mail_historiesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__mail_historiesClient<runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Mail_histories that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {mail_historiesFindUniqueOrThrowArgs} args - Arguments to find a Mail_histories
   * @example
   * // Get one Mail_histories
   * const mail_histories = await prisma.mail_histories.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends mail_historiesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, mail_historiesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__mail_historiesClient<runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mail_histories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mail_historiesFindFirstArgs} args - Arguments to find a Mail_histories
   * @example
   * // Get one Mail_histories
   * const mail_histories = await prisma.mail_histories.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends mail_historiesFindFirstArgs>(args?: Prisma.SelectSubset<T, mail_historiesFindFirstArgs<ExtArgs>>): Prisma.Prisma__mail_historiesClient<runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mail_histories that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mail_historiesFindFirstOrThrowArgs} args - Arguments to find a Mail_histories
   * @example
   * // Get one Mail_histories
   * const mail_histories = await prisma.mail_histories.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends mail_historiesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, mail_historiesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__mail_historiesClient<runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Mail_histories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mail_historiesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Mail_histories
   * const mail_histories = await prisma.mail_histories.findMany()
   * 
   * // Get first 10 Mail_histories
   * const mail_histories = await prisma.mail_histories.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mail_historiesWithIdOnly = await prisma.mail_histories.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends mail_historiesFindManyArgs>(args?: Prisma.SelectSubset<T, mail_historiesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Mail_histories.
   * @param {mail_historiesCreateArgs} args - Arguments to create a Mail_histories.
   * @example
   * // Create one Mail_histories
   * const Mail_histories = await prisma.mail_histories.create({
   *   data: {
   *     // ... data to create a Mail_histories
   *   }
   * })
   * 
   */
  create<T extends mail_historiesCreateArgs>(args: Prisma.SelectSubset<T, mail_historiesCreateArgs<ExtArgs>>): Prisma.Prisma__mail_historiesClient<runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Mail_histories.
   * @param {mail_historiesCreateManyArgs} args - Arguments to create many Mail_histories.
   * @example
   * // Create many Mail_histories
   * const mail_histories = await prisma.mail_histories.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends mail_historiesCreateManyArgs>(args?: Prisma.SelectSubset<T, mail_historiesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Mail_histories and returns the data saved in the database.
   * @param {mail_historiesCreateManyAndReturnArgs} args - Arguments to create many Mail_histories.
   * @example
   * // Create many Mail_histories
   * const mail_histories = await prisma.mail_histories.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Mail_histories and only return the `id`
   * const mail_historiesWithIdOnly = await prisma.mail_histories.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends mail_historiesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, mail_historiesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Mail_histories.
   * @param {mail_historiesDeleteArgs} args - Arguments to delete one Mail_histories.
   * @example
   * // Delete one Mail_histories
   * const Mail_histories = await prisma.mail_histories.delete({
   *   where: {
   *     // ... filter to delete one Mail_histories
   *   }
   * })
   * 
   */
  delete<T extends mail_historiesDeleteArgs>(args: Prisma.SelectSubset<T, mail_historiesDeleteArgs<ExtArgs>>): Prisma.Prisma__mail_historiesClient<runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Mail_histories.
   * @param {mail_historiesUpdateArgs} args - Arguments to update one Mail_histories.
   * @example
   * // Update one Mail_histories
   * const mail_histories = await prisma.mail_histories.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends mail_historiesUpdateArgs>(args: Prisma.SelectSubset<T, mail_historiesUpdateArgs<ExtArgs>>): Prisma.Prisma__mail_historiesClient<runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Mail_histories.
   * @param {mail_historiesDeleteManyArgs} args - Arguments to filter Mail_histories to delete.
   * @example
   * // Delete a few Mail_histories
   * const { count } = await prisma.mail_histories.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends mail_historiesDeleteManyArgs>(args?: Prisma.SelectSubset<T, mail_historiesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mail_histories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mail_historiesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Mail_histories
   * const mail_histories = await prisma.mail_histories.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends mail_historiesUpdateManyArgs>(args: Prisma.SelectSubset<T, mail_historiesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mail_histories and returns the data updated in the database.
   * @param {mail_historiesUpdateManyAndReturnArgs} args - Arguments to update many Mail_histories.
   * @example
   * // Update many Mail_histories
   * const mail_histories = await prisma.mail_histories.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Mail_histories and only return the `id`
   * const mail_historiesWithIdOnly = await prisma.mail_histories.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends mail_historiesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, mail_historiesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Mail_histories.
   * @param {mail_historiesUpsertArgs} args - Arguments to update or create a Mail_histories.
   * @example
   * // Update or create a Mail_histories
   * const mail_histories = await prisma.mail_histories.upsert({
   *   create: {
   *     // ... data to create a Mail_histories
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Mail_histories we want to update
   *   }
   * })
   */
  upsert<T extends mail_historiesUpsertArgs>(args: Prisma.SelectSubset<T, mail_historiesUpsertArgs<ExtArgs>>): Prisma.Prisma__mail_historiesClient<runtime.Types.Result.GetResult<Prisma.$mail_historiesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Mail_histories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mail_historiesCountArgs} args - Arguments to filter Mail_histories to count.
   * @example
   * // Count the number of Mail_histories
   * const count = await prisma.mail_histories.count({
   *   where: {
   *     // ... the filter for the Mail_histories we want to count
   *   }
   * })
  **/
  count<T extends mail_historiesCountArgs>(
    args?: Prisma.Subset<T, mail_historiesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Mail_historiesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Mail_histories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Mail_historiesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Mail_historiesAggregateArgs>(args: Prisma.Subset<T, Mail_historiesAggregateArgs>): Prisma.PrismaPromise<GetMail_historiesAggregateType<T>>

  /**
   * Group by Mail_histories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mail_historiesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends mail_historiesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: mail_historiesGroupByArgs['orderBy'] }
      : { orderBy?: mail_historiesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, mail_historiesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMail_historiesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the mail_histories model
 */
readonly fields: mail_historiesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for mail_histories.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__mail_historiesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the mail_histories model
 */
export interface mail_historiesFieldRefs {
  readonly id: Prisma.FieldRef<"mail_histories", 'String'>
  readonly user_id: Prisma.FieldRef<"mail_histories", 'String'>
  readonly audit_log_id: Prisma.FieldRef<"mail_histories", 'String'>
  readonly scene: Prisma.FieldRef<"mail_histories", 'String'>
  readonly tone: Prisma.FieldRef<"mail_histories", 'String'>
  readonly recipient_name: Prisma.FieldRef<"mail_histories", 'String'>
  readonly sender_name: Prisma.FieldRef<"mail_histories", 'String'>
  readonly core_points: Prisma.FieldRef<"mail_histories", 'String'>
  readonly mail_content: Prisma.FieldRef<"mail_histories", 'String'>
  readonly is_favorite: Prisma.FieldRef<"mail_histories", 'Boolean'>
  readonly is_deleted: Prisma.FieldRef<"mail_histories", 'Boolean'>
  readonly created_time: Prisma.FieldRef<"mail_histories", 'DateTime'>
  readonly updated_time: Prisma.FieldRef<"mail_histories", 'DateTime'>
}
    

// Custom InputTypes
/**
 * mail_histories findUnique
 */
export type mail_historiesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
  /**
   * Filter, which mail_histories to fetch.
   */
  where: Prisma.mail_historiesWhereUniqueInput
}

/**
 * mail_histories findUniqueOrThrow
 */
export type mail_historiesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
  /**
   * Filter, which mail_histories to fetch.
   */
  where: Prisma.mail_historiesWhereUniqueInput
}

/**
 * mail_histories findFirst
 */
export type mail_historiesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
  /**
   * Filter, which mail_histories to fetch.
   */
  where?: Prisma.mail_historiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of mail_histories to fetch.
   */
  orderBy?: Prisma.mail_historiesOrderByWithRelationInput | Prisma.mail_historiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for mail_histories.
   */
  cursor?: Prisma.mail_historiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` mail_histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` mail_histories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of mail_histories.
   */
  distinct?: Prisma.Mail_historiesScalarFieldEnum | Prisma.Mail_historiesScalarFieldEnum[]
}

/**
 * mail_histories findFirstOrThrow
 */
export type mail_historiesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
  /**
   * Filter, which mail_histories to fetch.
   */
  where?: Prisma.mail_historiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of mail_histories to fetch.
   */
  orderBy?: Prisma.mail_historiesOrderByWithRelationInput | Prisma.mail_historiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for mail_histories.
   */
  cursor?: Prisma.mail_historiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` mail_histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` mail_histories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of mail_histories.
   */
  distinct?: Prisma.Mail_historiesScalarFieldEnum | Prisma.Mail_historiesScalarFieldEnum[]
}

/**
 * mail_histories findMany
 */
export type mail_historiesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
  /**
   * Filter, which mail_histories to fetch.
   */
  where?: Prisma.mail_historiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of mail_histories to fetch.
   */
  orderBy?: Prisma.mail_historiesOrderByWithRelationInput | Prisma.mail_historiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing mail_histories.
   */
  cursor?: Prisma.mail_historiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` mail_histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` mail_histories.
   */
  skip?: number
  distinct?: Prisma.Mail_historiesScalarFieldEnum | Prisma.Mail_historiesScalarFieldEnum[]
}

/**
 * mail_histories create
 */
export type mail_historiesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
  /**
   * The data needed to create a mail_histories.
   */
  data: Prisma.XOR<Prisma.mail_historiesCreateInput, Prisma.mail_historiesUncheckedCreateInput>
}

/**
 * mail_histories createMany
 */
export type mail_historiesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many mail_histories.
   */
  data: Prisma.mail_historiesCreateManyInput | Prisma.mail_historiesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * mail_histories createManyAndReturn
 */
export type mail_historiesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
  /**
   * The data used to create many mail_histories.
   */
  data: Prisma.mail_historiesCreateManyInput | Prisma.mail_historiesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * mail_histories update
 */
export type mail_historiesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
  /**
   * The data needed to update a mail_histories.
   */
  data: Prisma.XOR<Prisma.mail_historiesUpdateInput, Prisma.mail_historiesUncheckedUpdateInput>
  /**
   * Choose, which mail_histories to update.
   */
  where: Prisma.mail_historiesWhereUniqueInput
}

/**
 * mail_histories updateMany
 */
export type mail_historiesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update mail_histories.
   */
  data: Prisma.XOR<Prisma.mail_historiesUpdateManyMutationInput, Prisma.mail_historiesUncheckedUpdateManyInput>
  /**
   * Filter which mail_histories to update
   */
  where?: Prisma.mail_historiesWhereInput
  /**
   * Limit how many mail_histories to update.
   */
  limit?: number
}

/**
 * mail_histories updateManyAndReturn
 */
export type mail_historiesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
  /**
   * The data used to update mail_histories.
   */
  data: Prisma.XOR<Prisma.mail_historiesUpdateManyMutationInput, Prisma.mail_historiesUncheckedUpdateManyInput>
  /**
   * Filter which mail_histories to update
   */
  where?: Prisma.mail_historiesWhereInput
  /**
   * Limit how many mail_histories to update.
   */
  limit?: number
}

/**
 * mail_histories upsert
 */
export type mail_historiesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
  /**
   * The filter to search for the mail_histories to update in case it exists.
   */
  where: Prisma.mail_historiesWhereUniqueInput
  /**
   * In case the mail_histories found by the `where` argument doesn't exist, create a new mail_histories with this data.
   */
  create: Prisma.XOR<Prisma.mail_historiesCreateInput, Prisma.mail_historiesUncheckedCreateInput>
  /**
   * In case the mail_histories was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.mail_historiesUpdateInput, Prisma.mail_historiesUncheckedUpdateInput>
}

/**
 * mail_histories delete
 */
export type mail_historiesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
  /**
   * Filter which mail_histories to delete.
   */
  where: Prisma.mail_historiesWhereUniqueInput
}

/**
 * mail_histories deleteMany
 */
export type mail_historiesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which mail_histories to delete
   */
  where?: Prisma.mail_historiesWhereInput
  /**
   * Limit how many mail_histories to delete.
   */
  limit?: number
}

/**
 * mail_histories without action
 */
export type mail_historiesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mail_histories
   */
  select?: Prisma.mail_historiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mail_histories
   */
  omit?: Prisma.mail_historiesOmit<ExtArgs> | null
}
